### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ishanjirety**

### CODE REVIEW

**Comment by ishanjirety** [comment]
This looks good

**Review by Akshaay9 — COMMENTED** [review]
Looking Good..

**Comment by vvaibhavdesai** [comment]
this looks good

**Comment by ishanjirety** [comment]
This looks good can be merged now

**Comment by shivamupadhyay008** [comment]
can be improved

**Comment by purvasheth** [comment]
Ye practice hai kya?

**Pull request merged**
